version: '3.1'
services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - ./mailpit:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 0
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_AUTH_FILE: /data/authfile
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'readfort'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5432:5432'
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./pgdata:/var/lib/postgresql/data
